<a href="https://colab.research.google.com/github/prasadw350-lang/Assignments/blob/main/Assignment25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [3]:
iris = load_iris()

X = iris.data
y = iris.target

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.33,
    random_state=42
)

In [5]:
neighbors = [3, 5, 7, 11, 13, 15]

accuracy = []
for k in neighbors:
    model = KNeighborsClassifier(n_neighbors=k)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    accuracy.append(acc)

    print(f"n_neighbors = {k}  Accuracy = {acc:.4f}")

n_neighbors = 3  Accuracy = 0.9800
n_neighbors = 5  Accuracy = 0.9800
n_neighbors = 7  Accuracy = 0.9800
n_neighbors = 11  Accuracy = 1.0000
n_neighbors = 13  Accuracy = 1.0000
n_neighbors = 15  Accuracy = 1.0000

In [6]:
comparison = pd.DataFrame({
    "n_neighbors": neighbors,
    "Accuracy": accuracy
})

comparison

   n_neighbors  Accuracy
0            3      0.98
1            5      0.98
2            7      0.98
3           11      1.00
4           13      1.00
5           15      1.00

In [7]:
best_k = comparison.loc[comparison["Accuracy"].idxmax()]

print("Best n_neighbors:", best_k["n_neighbors"])
print("Highest Accuracy:", best_k["Accuracy"])

Best n_neighbors: 11.0
Highest Accuracy: 1.0

(Manual Hyperparameter Tuning – SVM)

In [8]:
from sklearn.svm import SVC

In [9]:
C_values = [1, 10, 20]
kernels = ["linear", "rbf"]

results = []

for c in C_values:
    for kernel in kernels:

        model = SVC(C=c, kernel=kernel)

        model.fit(X_train, y_train)

        y_pred = model.predict(X_test)

        acc = accuracy_score(y_test, y_pred)

        results.append([c, kernel, acc])

        print(f"C = {c}, Kernel = {kernel}, Accuracy = {acc:.4f}")

C = 1, Kernel = linear, Accuracy = 1.0000
C = 1, Kernel = rbf, Accuracy = 1.0000
C = 10, Kernel = linear, Accuracy = 1.0000
C = 10, Kernel = rbf, Accuracy = 0.9800
C = 20, Kernel = linear, Accuracy = 0.9800
C = 20, Kernel = rbf, Accuracy = 1.0000

In [10]:
comparison_svm = pd.DataFrame(
    results,
    columns=["C", "Kernel", "Accuracy"]
)

comparison_svm

    C  Kernel  Accuracy
0   1  linear      1.00
1   1     rbf      1.00
2  10  linear      1.00
3  10     rbf      0.98
4  20  linear      0.98
5  20     rbf      1.00

In [11]:
best_svm = comparison_svm.loc[comparison_svm["Accuracy"].idxmax()]

print("Best C:", best_svm["C"])
print("Best Kernel:", best_svm["Kernel"])
print("Best Accuracy:", best_svm["Accuracy"])

Best C: 1
Best Kernel: linear
Best Accuracy: 1.0

(Grid Search CV)

In [12]:
from sklearn.model_selection import GridSearchCV

In [13]:
param_grid = {
    "C": [1, 10, 20],
    "kernel": ["linear", "rbf"]
}

In [14]:
grid = GridSearchCV(
    estimator=SVC(),
    param_grid=param_grid,
    cv=5
)

In [15]:
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 10, 20], 'kernel': ['linear', 'rbf']})

In [16]:
results = pd.DataFrame(grid.cv_results_)

results[["param_C", "param_kernel", "mean_test_score"]]

   param_C param_kernel  mean_test_score
0        1       linear             0.95
1        1          rbf             0.93
2       10       linear             0.93
3       10          rbf             0.94
4       20       linear             0.93
5       20          rbf             0.95

In [17]:
print("Best Parameters:", grid.best_params_)
print("Best Score:", grid.best_score_)

Best Parameters: {'C': 1, 'kernel': 'linear'}
Best Score: 0.95

RandomizedSearchCV (SVM)

In [18]:
from sklearn.model_selection import RandomizedSearchCV

In [19]:
param_dist = {
    "C": [1, 10, 20],
    "kernel": ["linear", "rbf"]
}

In [20]:
random = RandomizedSearchCV(
    estimator=SVC(),
    param_distributions=param_dist,
    n_iter=5,
    cv=5,
    random_state=42
)

In [21]:
random.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=SVC(), n_iter=5,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['linear', 'rbf']},
                   random_state=42)

In [22]:
random_results = pd.DataFrame(random.cv_results_)

random_results[["param_C", "param_kernel", "mean_test_score"]]

   param_C param_kernel  mean_test_score
0        1       linear             0.95
1        1          rbf             0.93
2       20          rbf             0.95
3       10       linear             0.93
4       20       linear             0.93

In [23]:
print("Best Parameters:", random.best_params_)
print("Best Score:", random.best_score_)

Best Parameters: {'kernel': 'linear', 'C': 1}
Best Score: 0.95

In [24]:
print("Grid Search Best Parameters :", grid.best_params_)
print("Grid Search Best Score :", grid.best_score_)

print()

print("Random Search Best Parameters :", random.best_params_)
print("Random Search Best Score :", random.best_score_)

Grid Search Best Parameters : {'C': 1, 'kernel': 'linear'}
Grid Search Best Score : 0.95

Random Search Best Parameters : {'kernel': 'linear', 'C': 1}
Random Search Best Score : 0.95

(Bagging – Random Forest)

In [25]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [26]:
X_train_rf, X_test_rf, y_train_rf, y_test_rf = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

In [27]:
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

In [28]:
rf.fit(X_train_rf, y_train_rf)

RandomForestClassifier(random_state=42)

In [29]:
rf_pred = rf.predict(X_test_rf)

In [30]:
rf_acc = accuracy_score(y_test_rf, rf_pred)

print("Accuracy:", rf_acc)

Accuracy: 0.9

Boosting – AdaBoost & Gradient Boosting

In [31]:
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier

In [32]:
ada = AdaBoostClassifier(
    n_estimators=100,
    random_state=42
)

ada.fit(X_train_rf, y_train_rf)

ada_pred = ada.predict(X_test_rf)

ada_acc = accuracy_score(y_test_rf, ada_pred)

print("AdaBoost Accuracy:", ada_acc)

AdaBoost Accuracy: 0.9333333333333333

In [33]:
gb = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

gb.fit(X_train_rf, y_train_rf)

gb_pred = gb.predict(X_test_rf)

gb_acc = accuracy_score(y_test_rf, gb_pred)

print("Gradient Boosting Accuracy:", gb_acc)

Gradient Boosting Accuracy: 0.9666666666666667

Boosting – XGBoost

In [35]:
from xgboost import XGBClassifier

In [36]:
xgb = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)

In [37]:
xgb.fit(X_train_rf, y_train_rf)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)

In [40]:
xgb_pred = xgb.predict(X_test_rf)

In [41]:
xgb_acc = accuracy_score(y_test_rf, xgb_pred)

print("XGBoost Accuracy:", xgb_acc)

XGBoost Accuracy: 0.9333333333333333

Hyperparameter Tuning on Random Forest (GridSearchCV)

In [42]:
from sklearn.model_selection import GridSearchCV

In [43]:
param_grid_rf = {
    "n_estimators": [50, 100, 150],
    "max_depth": [3, 5, 7]
}

In [44]:
grid_rf = GridSearchCV(
    estimator=RandomForestClassifier(random_state=42),
    param_grid=param_grid_rf,
    cv=5
)

In [45]:
grid_rf.fit(X_train_rf, y_train_rf)

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42),
             param_grid={'max_depth': [3, 5, 7],
                         'n_estimators': [50, 100, 150]})

In [46]:
rf_results = pd.DataFrame(grid_rf.cv_results_)

rf_results[["param_n_estimators", "param_max_depth", "mean_test_score"]]

   param_n_estimators  param_max_depth  mean_test_score
0                  50                3         0.958333
1                 100                3         0.958333
2                 150                3         0.958333
3                  50                5         0.950000
4                 100                5         0.950000
5                 150                5         0.950000
6                  50                7         0.950000
7                 100                7         0.950000
8                 150                7         0.950000

In [47]:
print("Best Parameters:", grid_rf.best_params_)
print("Best Score:", grid_rf.best_score_)

Best Parameters: {'max_depth': 3, 'n_estimators': 50}
Best Score: 0.9583333333333334

(Complete Model Comparison)

In [48]:
best_svm = SVC(
    C=grid.best_params_["C"],
    kernel=grid.best_params_["kernel"]
)

best_svm.fit(X_train_rf, y_train_rf)
svm_pred = best_svm.predict(X_test_rf)
svm_acc = accuracy_score(y_test_rf, svm_pred)

In [49]:
comparison = pd.DataFrame({
    "Algorithm": [
        "SVM",
        "Random Forest",
        "AdaBoost",
        "Gradient Boosting",
        "XGBoost"
    ],
    "Accuracy": [
        svm_acc,
        rf_acc,
        ada_acc,
        gb_acc,
        xgb_acc
    ]
})

comparison

           Algorithm  Accuracy
0                SVM  1.000000
1      Random Forest  0.900000
2           AdaBoost  0.933333
3  Gradient Boosting  0.966667
4            XGBoost  0.933333

In [50]:
best_model = comparison.loc[comparison["Accuracy"].idxmax()]

print("Best Model:", best_model["Algorithm"])
print("Accuracy:", best_model["Accuracy"])

Best Model: SVM
Accuracy: 1.0

In [51]:
print(
    f"{best_model['Algorithm']} performed the best with an accuracy of "
    f"{best_model['Accuracy']:.4f}."
)

SVM performed the best with an accuracy of 1.0000.

Mini Project – Full Pipeline

In [52]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

iris = load_iris()
X = iris.data
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [53]:
from sklearn.neighbors import KNeighborsClassifier
k_values = [3,5,7,11,13]
manual_results = []
for k in k_values:
    model = KNeighborsClassifier(n_neighbors=k)
    model.fit(X_train,y_train)
    acc = model.score(X_test,y_test)
    manual_results.append([k,acc])
manual_df = pd.DataFrame(
    manual_results,
    columns=["K","Accuracy"]
)
manual_df

    K  Accuracy
0   3  1.000000
1   5  1.000000
2   7  0.966667
3  11  1.000000
4  13  1.000000

In [54]:
from sklearn.model_selection import GridSearchCV
param_grid = {
    "n_neighbors":[3,5,7,11,13]
}
grid = GridSearchCV(
    KNeighborsClassifier(),
    param_grid,
    cv=5
)
grid.fit(X_train,y_train)
print(grid.best_params_)
print(grid.best_score_)

{'n_neighbors': 3}
0.9583333333333334

In [55]:
from sklearn.model_selection import RandomizedSearchCV

random = RandomizedSearchCV(
    KNeighborsClassifier(),
    param_grid,
    n_iter=3,
    cv=5,
    random_state=42
)
random.fit(X_train,y_train)
print(random.best_params_)
print(random.best_score_)

{'n_neighbors': 5}
0.9416666666666667

In [57]:
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)
rf.fit(X_train,y_train)
rf_acc = accuracy_score(
    y_test,
    rf.predict(X_test)
)

In [58]:
ada = AdaBoostClassifier(
    n_estimators=100,
    random_state=42
)

ada.fit(X_train,y_train)

ada_acc = accuracy_score(
    y_test,
    ada.predict(X_test)
)

In [59]:
gb = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)
gb.fit(X_train,y_train)
gb_acc = accuracy_score(
    y_test,
    gb.predict(X_test)
)

In [60]:
from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)
xgb.fit(X_train,y_train)
xgb_acc = accuracy_score(
    y_test,
    xgb.predict(X_test)
)

In [61]:
knn_best = grid.best_estimator_

knn_acc = accuracy_score(
    y_test,
    knn_best.predict(X_test)
)
comparison = pd.DataFrame({

    "Algorithm":[
        "KNN",
        "Random Forest",
        "AdaBoost",
        "Gradient Boosting",
        "XGBoost"
    ],
    "Accuracy":[
        knn_acc,
        rf_acc,
        ada_acc,
        gb_acc,
        xgb_acc
    ]
})
comparison

           Algorithm  Accuracy
0                KNN  1.000000
1      Random Forest  1.000000
2           AdaBoost  0.933333
3  Gradient Boosting  1.000000
4            XGBoost  1.000000

In [63]:
best = comparison.loc[
    comparison["Accuracy"].idxmax()
]

print(best)

Algorithm    KNN
Accuracy     1.0
Name: 0, dtype: object

In [64]:
import joblib

joblib.dump(
    knn_best,
    "Best_Model.pkl"
)

['Best_Model.pkl']