<a href="https://colab.research.google.com/github/prasadw350-lang/Assignments/blob/main/Assignment25_Optional.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [73]:
# Import Libraries

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Load Dataset
filename = "/content/drive/MyDrive/Titanic-Dataset.csv"
df = pd.read_csv(filename)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [74]:
# Check Dataset

df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [75]:
# Handle Missing Values

df["Age"] = df["Age"].fillna(df["Age"].median())

df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

df.drop("Cabin", axis=1, inplace=True)

In [76]:
# Check Dataset

df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [77]:
df.drop(
    ["PassengerId", "Name", "Ticket"],
    axis=1,
    inplace=True
)

In [78]:
# Preprocessing

df = pd.get_dummies(df, drop_first=True)

In [79]:
# Features & Target

X = df.drop("Survived", axis=1)
y = df["Survived"]

In [80]:
# Train-Test Split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [81]:
# Feature Scaling

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [82]:
log = LogisticRegression()

log.fit(X_train, y_train)
log_acc = accuracy_score(y_test, log.predict(X_test))
print("Logistic Regression:", log_acc)

Logistic Regression: 0.8100558659217877

In [83]:
dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train, y_train)
dt_acc = accuracy_score(y_test, dt.predict(X_test))
print("Decision Tree:", dt_acc)

Decision Tree: 0.7821229050279329

In [84]:
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)
knn_acc = accuracy_score(y_test, knn.predict(X_test))
print("KNN:", knn_acc)

KNN: 0.8044692737430168

In [85]:
nb = GaussianNB()

nb.fit(X_train, y_train)
nb_acc = accuracy_score(y_test, nb.predict(X_test))
print("Naive Bayes:", nb_acc)

Naive Bayes: 0.770949720670391

In [86]:
svm = SVC()

svm.fit(X_train, y_train)
svm_acc = accuracy_score(y_test, svm.predict(X_test))
print("SVM:", svm_acc)

SVM: 0.8212290502793296

In [87]:
for k in [3,5,7,9]:

    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    print("K =", k,
          "Accuracy =", accuracy_score(y_test, knn.predict(X_test)))

K = 3 Accuracy = 0.7877094972067039
K = 5 Accuracy = 0.8044692737430168
K = 7 Accuracy = 0.8044692737430168
K = 9 Accuracy = 0.7932960893854749

In [88]:
for c in [1,10]:

    for kernel in ["linear","rbf"]:
        svm = SVC(C=c, kernel=kernel)
        svm.fit(X_train, y_train)
        print("C =", c,
              "Kernel =", kernel,
              "Accuracy =", accuracy_score(y_test, svm.predict(X_test)))

C = 1 Kernel = linear Accuracy = 0.7821229050279329
C = 1 Kernel = rbf Accuracy = 0.8212290502793296
C = 10 Kernel = linear Accuracy = 0.7821229050279329
C = 10 Kernel = rbf Accuracy = 0.8100558659217877

In [89]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    "C":[1,10],
    "kernel":["linear","rbf"]
}
grid = GridSearchCV(SVC(), param_grid, cv=5)
grid.fit(X_train, y_train)
print("Best Parameters:", grid.best_params_)
print("Best Score:", grid.best_score_)

Best Parameters: {'C': 1, 'kernel': 'rbf'}
Best Score: 0.8314291342460358

In [90]:
from sklearn.model_selection import RandomizedSearchCV

random = RandomizedSearchCV(
    SVC(),
    param_distributions=param_grid,
    n_iter=2,
    cv=5,
    random_state=42
)

random.fit(X_train, y_train)

print("Best Parameters:", random.best_params_)
print("Best Score:", random.best_score_)

Best Parameters: {'kernel': 'rbf', 'C': 1}
Best Score: 0.8314291342460358

In [91]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)
rf.fit(X_train, y_train)
rf_acc = accuracy_score(y_test, rf.predict(X_test))
print("Random Forest Accuracy:", rf_acc)

Random Forest Accuracy: 0.8212290502793296

In [92]:
comparison = pd.DataFrame({

    "Algorithm":[
        "Logistic Regression",
        "Decision Tree",
        "KNN",
        "Naive Bayes",
        "SVM",
        "Random Forest"
    ],

    "Accuracy":[
        log_acc,
        dt_acc,
        knn_acc,
        nb_acc,
        svm_acc,
        rf_acc
    ]

})

print(comparison)

             Algorithm  Accuracy
0  Logistic Regression  0.810056
1        Decision Tree  0.782123
2                  KNN  0.804469
3          Naive Bayes  0.770950
4                  SVM  0.821229
5        Random Forest  0.821229

In [94]:
import joblib

joblib.dump(rf, "RF_Titanic.pkl")
joblib.dump(scaler, "RF_TScaler.pkl")
joblib.dump(X.columns.tolist(), "RF_TColumns.pkl")

['RF_TColumns.pkl']